version: "3.2"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ='Europe/Stockholm'
      - WEBUI_PORT=8090
      - TORRENTING_PORT=6881
    volumes:
      # - type: bind
      #   source: /mnt/data/qbittorrent
      #   target: /config
      # - type: bind
      #   source: /downloads
      #   target: /downloads #optional
      - /mnt/data/qbittorrent:/config
      - /downloads:/downloads

    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    networks:
      - arr_network
    restart: unless-stopped

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]


networks:
  arr_network:
    driver: overlay
    attachable: true