- name: include vault
  ansible.builtin.include_vars:
    file: vault.yml

- name: utility present
  apt:
    name:
      - cifs-utils
    state: present

- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
        
- name: Mount network share
  ansible.posix.mount:
    src: "{{ uri }}"
    path: "{{ mountpoint }}"
    fstype: cifs
    opts: 'username={{ username }},password={{ password }}'
    state: mounted