---
# Install bind
- name: Install bind
  ansible.builtin.apt:
    name:
      - bind9
    update_cache: true

# disable and stop systemd resolver
- name: disable systemd resolver
  service:
    name: systemd-resolved.service
    enabled: false

- name: stop systemd resolver
  service:
    name: systemd-resolved.service
    state: stopped
    
# update resolv.conf
- name: updating resolv.conf
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: create zone dir if not exist
  file:
    path: /etc/bind/zones
    state: directory

# Update Master DNS

- name: updating master bind options
  ansible.builtin.copy:
    src: master.named.conf.options
    dest: /etc/bind/named.conf.options
  when: type == "master"
  notify: restart-bind

- name: updating master draups com zone
  ansible.builtin.copy:
    src: db.draups.com
    dest: /etc/bind/zones/db.draups.com
  when: type == "master"
  notify: restart-bind

- name: updating master draups home zone
  ansible.builtin.copy:
    src: db.draups.home
    dest: /etc/bind/zones/db.draups.home
  when: type == "master"
  notify: restart-bind

- name: updating master named conf local
  ansible.builtin.copy:
    src: master.named.conf.local
    dest: /etc/bind/named.conf.local
  when: type == "master"
  notify: restart-bind

  # update secondary 
  
- name: updating secondary bind options
  ansible.builtin.copy:
    src: secondary.named.conf.options
    dest: /etc/bind/named.conf.options
  when: type == "secondary"

- name: updating secondary named conf local
  ansible.builtin.copy:
    src: secondary.named.conf.local
    dest: /etc/bind/named.conf.local
  when: type == "secondary"
  notify: restart-bind
