---
version: "3.2"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex

    environment:
      - PUID=0
      - PGID=0
      - TZ='Europe/Stockholm'
      - VERSION=docker
    volumes:
      - /mnt/data/plex:/config
      - /downloads/tv:/tv
      - /downloads/movies:/movies
      - /downloads/other:/other
    restart: unless-stopped
    
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]