- name: Authenticate with Pi-hole API
  shell: |
    curl -X POST "{{ endpoint }}/auth" \
      -H "accept: application/json" \
      -H "content-type: application/json" \
      -d '{"password":"{{ webpassword }}"}'
  register: api_auth_response

- name: Show API auth response
  debug:
    var: api_auth_response

- name: Parse API auth response
  set_fact:
    api_sid: "{{ api_auth_response.stdout | from_json | json_query('session.sid') }}"
    api_csrf: "{{ api_auth_response.stdout | from_json | json_query('session.csrf') }}"

- name: Show extracted sid and csrf for debugging
  debug:
    msg:
      - "sid: {{ api_sid }}"
      - "csrf: {{ api_csrf }}"

- name: Read local-dns.list and extract dns hosts
  set_fact:
    dns_hosts: "{{ lookup('file', '../files/arecords.list') }}"

- name: Prepare dns hosts for the payload
  set_fact:
    dns_hosts_converted: "{{ dns_hosts.split('\n') | map('regex_replace', '^(.*)$', '\"\\1\"') | join(',\n') }}"

- name: Ouput dns hosts with quotes
  debug:
    var: dns_hosts_converted

- name: Send the updated DNS hosts to the API
  shell: |
    curl -X PATCH "{{ endpoint }}/config" \
      -H "accept: application/json" \
      -H "content-type: application/json" \
      -H "X-FTL-SID: {{ api_sid }}" \
      -d '{
        "config": {
          "dns": {
            "hosts": [
              {{ dns_hosts_converted }}
            ]
          }
        }
      }'
