- hosts: all
  become: true
  
  tasks:
    - name: Bare include (free-form)
      ansible.builtin.include_vars: ../vars/vault.yml

    - name: apt
      apt:
        update_cache: yes
        upgrade: yes

    - name: Check that the reboot-required exists
      stat:
        path: /var/run/reboot-required
      register: p
    - debug:
        msg: "Reboot required"
      when: p.stat.exists

    - name: Send a message to the Discord channel with specific username and avatar
      community.general.discord:
        webhook_id: "{{ webhook_id }}"
        webhook_token: "{{ webhook_token }}"
        content: "Reboot required: {{ inventory_hostname }}"
        username: Ansible
        avatar_url: "https://docs.ansible.com/ansible/latest/_static/images/logo_invert.png"
      throttle: 1
      when: p.stat.exists