---
- name: Install docker swarm
  hosts: all
  become: true


    
  tasks:
    # - name: Add user to docker group
    #   user:
    #     name: draup
    #     group: docker

    # - name: Prints ad addr
    #   ansible.builtin.debug:
    #     msg:
    #     - "{{ ansible_become_user }}"
      
    - name: check/init swarm
      community.docker.docker_swarm:
        state: present
        advertise_addr: 192.168.100.10:2377
      register: __output_swarm
      when: inventory_hostname in groups['managers'][0]

    # - name: install manager
    #   docker_swarm:
    #     state: join
    #     timeout: 60
    #     advertise_addr: "{{ inventory_hostname }}":2377
    #     join_token: "{{ hostvars[groups['managers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Manager']}}"
    #     remote_addrs: "{{ groups['managers'][0] }}"
    #   when: inventory_hostname in groups['managers'] and inventory_hostname not in groups['managers'][0]

    # - name: install worker
    #   docker_swarm:
    #     state: join
    #     timeout: 60
    #     advertise_addr: "{{ inventory_hostname }}":2377
    #     join_token: "{{ hostvars[groups['managers'][0]]['__output_swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    #     remote_addrs: "{{ groups['managers'][0] }}"
    #   when: inventory_hostname in groups['workers']