---
- hosts: managers
  become: true
  gather_facts: false

  tasks:

  - blockinfile:
      state: absent
      dest: /etc/hosts
      content: |
        {% for host in groups.gluster_nodes %}
        {{ host }} {{ hostvars[host].hostname}}
        {% endfor %}