---
- hosts: all
  become: true
  vars_files: 
  - vars/vault.yaml

  pre_tasks:
  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false


- hosts: all
  become: true
  roles:
    - base

- hosts: keepalived
  become: true
  roles:
    - keepalived

- hosts: managers
  become: true
  roles:
    - managers
    - docker

- hosts: workers
  become: true
  roles:
     - workers
     - docker

- hosts: plex
  become: true
  roles:
     - plex
