---
# Install bind
- name: Install ansible
  ansible.builtin.apt:
    name:
      - ansible
    update_cache: true

# Copy key
- name: copy ansible key
  ansible.builtin.copy:
    src: ~/.ssh/ansible
    dest: /home/ansible/.ssh/ansible

    # Copy key
- name: copy vault key
  ansible.builtin.copy:
    src: ~/.vault.key
    dest: /home/ansible/.vault.key