- name: utility present
  apt:
    name:
      - cifs-utils
    state: present

- name: check mountpoint exist
  file:
    path: "/downloads"
    state: directory
    mode: '0777'
    owner: 0
    group: 0

- name: mount network share
  mount:
    src: "//192.168.1.25/downloads"
    path: "/downloads"
    fstype: cifs
    opts: 'rw,vers=3,file_mode=0600,dir_mode=0700,credentials=/mnt/data/smb/smb.txt'
    state: mounted