on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * 0' 

jobs:
  run-ansible:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: run ansible playbook
        run: |
          cd ansible
          ansible-playbook playbooks/apt-update.yaml
