on:
  workflow_dispatch:
  schedule:
    - cron:  '30 11 * * 0' 

jobs:
  run-ansible:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: run ansible playbook
        run: |
          cd ansible
          ansible-playbook playbooks/apt-upgrade.yaml
