on:
  push:
    branches:
      - main
    paths:
      - 'ansible/roles/bind/files/**'

jobs:
  run-ansible:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: run ansible playbook
        run: |
          cd ansible
          ansible-playbook dns.yml
